/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Test */

#ifndef _Included_Test
#define _Included_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Test
 * Method:    invokeNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)[B
 */JNIEXPORT jbyteArray JNICALL Java_me_sheimi_pig_eval_BytesNativeEvalFunc_invokeNative(
        JNIEnv *, jclass, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
