/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_sheimi_pig_eval_BytesStringNativeEvalFunc */

#ifndef _Included_me_sheimi_pig_eval_BytesStringNativeEvalFunc
#define _Included_me_sheimi_pig_eval_BytesStringNativeEvalFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_sheimi_pig_eval_BytesStringNativeEvalFunc
 * Method:    invokeNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;[B)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_me_sheimi_pig_eval_BytesStringNativeEvalFunc_invokeNative(
		JNIEnv *, jclass, jstring, jstring, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
