/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class me_sheimi_pig_eval_BytesNativeEvalFunc */

#ifndef _Included_me_sheimi_pig_eval_BytesNativeEvalFunc
#define _Included_me_sheimi_pig_eval_BytesNativeEvalFunc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     me_sheimi_pig_eval_BytesNativeEvalFunc
 * Method:    invokeNative
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_me_sheimi_pig_eval_BytesNativeEvalFunc_invokeNative
  (JNIEnv *, jclass, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
